// blocks/block-map.js

export const BlockMap = {
  // ---------------- MOTION ----------------
  "motion_movesteps": "motion_moveSteps",
  "motion_turnright": "motion_turnRight",
  "motion_turnleft": "motion_turnLeft",
  "motion_goto": "motion_goTo",
  "motion_gotoxy": "motion_goToXY",
  "motion_glideto": "motion_glideTo",
  "motion_glidexy": "motion_glideXY",
  "motion_pointindirection": "motion_pointInDirection",
  "motion_pointtowards": "motion_pointTowards",
  "motion_changexby": "motion_changeXBy",
  "motion_setx": "motion_setX",
  "motion_changeyby": "motion_changeYBy",
  "motion_sety": "motion_setY",
  "motion_ifonedgebounce": "motion_ifOnEdgeBounce",
  "motion_setrotationstyle": "motion_setRotationStyle",

  // ---------------- LOOKS ----------------
  "looks_say": "looks_say",
  "looks_sayforsecs": "looks_sayForSecs",
  "looks_think": "looks_think",
  "looks_thinkforsecs": "looks_thinkForSecs",
  "looks_show": "looks_show",
  "looks_hide": "looks_hide",
  "looks_switchcostumeto": "looks_switchCostumeTo",
  "looks_nextcostume": "looks_nextCostume",
  "looks_switchbackdropto": "looks_switchBackdropTo",
  "looks_nextbackdrop": "looks_nextBackdrop",
  "looks_changeeffectby": "looks_changeEffectBy",
  "looks_seteffectto": "looks_setEffectTo",
  "looks_cleargraphiceffects": "looks_clearGraphicEffects",
  "looks_changesizeby": "looks_changeSizeBy",
  "looks_setsizeto": "looks_setSizeTo",
  "looks_gotofrontback": "looks_goToFrontBack",
  "looks_goforwardbackwardlayers": "looks_goForwardBackwardLayers",

  // ---------------- SOUND ----------------
  "sound_play": "sound_play",
  "sound_playuntildone": "sound_playUntilDone",
  "sound_stopallsounds": "sound_stopAllSounds",
  "sound_playdrumforbeats": "sound_playDrumForBeats",
  "sound_restforbeats": "sound_restForBeats",
  "sound_playnoteforbeats": "sound_playNoteForBeats",
  "sound_setinstrument": "sound_setInstrument",
  "sound_changeeffectby": "sound_changeEffectBy",
  "sound_seteffectto": "sound_setEffectTo",
  "sound_cleareffects": "sound_clearEffects",
  "sound_changevolumeby": "sound_changeVolumeBy",
  "sound_setvolumeto": "sound_setVolumeTo",

  // ---------------- EVENTS ----------------
  "event_whenflagclicked": "event_whenFlagClicked",
  "event_whenkeypressed": "event_whenKeyPressed",
  "event_whenthisspriteclicked": "event_whenThisSpriteClicked",
  "event_whenbackdropswitchesto": "event_whenBackdropSwitchesTo",
  "event_whengreaterthan": "event_whenGreaterThan",
  "event_whenbroadcastreceived": "event_whenBroadcastReceived",
  "event_broadcast": "event_broadcast",
  "event_broadcastandwait": "event_broadcastAndWait",

  // ---------------- CONTROL ----------------
  "control_wait": "control_wait",
  "control_repeat": "control_repeat",
  "control_forever": "control_forever",
  "control_if": "control_if",
  "control_if_else": "control_ifElse",
  "control_wait_until": "control_waitUntil",
  "control_repeat_until": "control_repeatUntil",
  "control_stop": "control_stop",
  "control_start_as_clone": "control_startAsClone",
  "control_create_clone_of": "control_createCloneOf",
  "control_delete_this_clone": "control_deleteThisClone",

  // ---------------- SENSING ----------------
  "sensing_touchingobject": "sensing_touchingObject",
  "sensing_touchingcolor": "sensing_touchingColor",
  "sensing_coloristouchingcolor": "sensing_colorIsTouchingColor",
  "sensing_distanceto": "sensing_distanceTo",
  "sensing_askandwait": "sensing_askAndWait",
  "sensing_answer": "sensing_answer",
  "sensing_keypressed": "sensing_keyPressed",
  "sensing_mousedown": "sensing_mouseDown",
  "sensing_mousex": "sensing_mouseX",
  "sensing_mousey": "sensing_mouseY",
  "sensing_setdragmode": "sensing_setDragMode",
  "sensing_loudness": "sensing_loudness",
  "sensing_timer": "sensing_timer",
  "sensing_resettimer": "sensing_resetTimer",
  "sensing_of": "sensing_of",
  "sensing_current": "sensing_current",
  "sensing_dayssince2000": "sensing_daysSince2000",
  "sensing_username": "sensing_username",

  // ---------------- OPERATORS ----------------
  "operator_add": "operator_add",
  "operator_subtract": "operator_subtract",
  "operator_multiply": "operator_multiply",
  "operator_divide": "operator_divide",
  "operator_random": "operator_random",
  "operator_lt": "operator_lt",
  "operator_equals": "operator_equals",
  "operator_gt": "operator_gt",
  "operator_and": "operator_and",
  "operator_or": "operator_or",
  "operator_not": "operator_not",
  "operator_join": "operator_join",
  "operator_letter_of": "operator_letterOf",
  "operator_length_of": "operator_lengthOf",
  "operator_contains": "operator_contains",
  "operator_mod": "operator_mod",
  "operator_round": "operator_round",
  "operator_mathop": "operator_mathOp",

  // ---------------- VARIABLES ----------------
  "data_setvariableto": "data_setVariableTo",
  "data_changevariableby": "data_changeVariableBy",
  "data_showvariable": "data_showVariable",
  "data_hidevariable": "data_hideVariable",

  // ---------------- LISTS ----------------
  "data_addtolist": "data_addToList",
  "data_deleteoflist": "data_deleteOfList",
  "data_deletealloflist": "data_deleteAllOfList",
  "data_insertatlist": "data_insertAtList",
  "data_replaceitemoflist": "data_replaceItemOfList",
  "data_itemoflist": "data_itemOfList",
  "data_lengthoflist": "data_lengthOfList",
  "data_listcontainsitem": "data_listContainsItem",
  "data_showlist": "data_showList",
  "data_hidelist": "data_hideList",

  // ---------------- CUSTOM BLOCKS ----------------
  "procedures_definition": "procedures_definition",
  "procedures_call": "procedures_call",
  "procedures_return": "procedures_return"
};
